version: "3"

services:
  leto:
    image: letoai/leto:latest
    container_name: leto
    user: "1000"
    build: .
    ports:
      - 8501:8501
    volumes:
      - ../leto:/usr/local/lib/python3.8/site-packages/leto
      - ../:/home/coder/leto
      - ../data/opennre/:/home/coder/.opennre
      - vscode-leto:/home/coder/.vscode-server
    working_dir: "/home/coder/leto"
    command: ["./docker/wait-for-it.sh", "neo4j:7687", "-t", "60", "--","streamlit", "run", "leto.py"]
    depends_on:
      - neo4j

  docs:
    image: letoai/docs:latest
    container_name: leto-docs
    build:
      dockerfile: docs.dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ..:/home/coder/leto
    working_dir: "/home/coder/leto"
    command: ["mkdocs", "serve", "-a", "0.0.0.0:8000"]

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
    volumes:
      - "../data/neo4j:/var/lib/neo4j/data"
      - "../data/neo4j-plugins:/var/lib/neo4j/plugins"
    environment:
      - NEO4J_AUTH=neo4j/letoai
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4JLABS_PLUGINS=["apoc"]

volumes:
  vscode-leto:
