FROM python:3.8

ARG USERNAME=coder
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN mkdir -p /home/$USERNAME/.vscode-server/extensions \
        /home/$USERNAME/.vscode-server-insiders/extensions \
    && chown -R $USERNAME \
        /home/$USERNAME/.vscode-server \
        /home/$USERNAME/.vscode-server-insiders

COPY requirements.txt /home/$USERNAME/requirements.txt
RUN pip install -r /home/$USERNAME/requirements.txt
RUN python3 -m coreferee install en

#setup OpenNRE
RUN git clone https://github.com/thunlp/OpenNRE.git \
    && pip install -r OpenNRE/requirements.txt \
    && python OpenNRE/setup.py install

USER $USERNAME
