name: Deploy Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Build docs
      run: mkdocs build

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: LETO-ai/leto-ai.github.io
        publish_branch: master
        publish_dir: ./site
